### ISSUE TITLE
Do something about white space in playlists

### ISSUE THREAD

**Issue by cisox** [suspendlabs/lstn#134]
https://www.dropbox.com/s/vkac0rjaloyon9f/Screenshot%202015-02-21%2023.46.26.png?dl=0

**Comment by fishfacemcgee** [comment]
"Something about" meaning what? We want more/less/etc.?

**Comment by cisox** [comment]
@fishfacemcgee What I mean by that is that we have a large amount of unused white space under the title that we don't have in other list items. That's mostly because we don't have anything to display here (result count, album count, track count, duration, etc). It would be nice to see if we could add more info about the playlists here or maybe reconsider how we're handling these type of list items.
