### ISSUE TITLE
Update the broadcasting button

### ISSUE THREAD

**Issue by cisox** [suspendlabs/lstn#145]
https://www.dropbox.com/s/6rcele8gpbv5ysy/Screenshot%202015-02-21%2023.53.35.png?dl=0

https://www.dropbox.com/s/qyj272p790qcw4x/Screenshot%202015-02-21%2023.53.44.png?dl=0

**Comment by mmattax** [comment]
Indicator will be added when #159 is merged.

**Comment by cisox** [comment]
It was suggested we change the text to "Join Broadcasters" to avoid confusion
