### ISSUE TITLE
Reimplement auto scrolling

### ISSUE THREAD

**Issue by cisox** [suspendlabs/lstn#155]
I killed it on move to top on purpose, but we'll want to re-add it to chat room messages and the queue. I'm imagining only auto scrolling if you're already at the bottom.

**Comment by fishfacemcgee** [comment]
@cisox Do we have a maximum height on the chat box yet? It looks like it goes forever.

**Comment by cisox** [comment]
@fishfacemcgee This should be fixed now. It may need some small style tweaks but the middle and right columns are both set to ~95% height and have an overflow-y of auto.

**Comment by cisox** [comment]
I closed the wrong issue. This isn't for making the boxes scroll, this is to make sure that we scroll to the bottom on new activity/etc.
