### ISSUE TITLE
Why is the Now Playing Area not Squarish?

### ISSUE THREAD

**Issue by fishfacemcgee** [suspendlabs/lstn#172]
Ignoring the intense resolution mismatch, it seems weird that we would explicitly display the album art in a way that it'd be cut off:

<img src="https://s3.amazonaws.com/f.cl.ly/items/2e1n3Z0E0k3F0X3y3C3U/Screen%20Shot%202015-02-22%20at%203.40.52%20PM.png" />

It kinda looks like that in the mockup, so I'm wondering if we should overrule that, to force it to a (300x300?) square.

**Comment by cisox** [comment]
That seems reasonable to me. Probably worth pinging Matt about his ideas around how to use that space but a square sounds like a good idea for that.

**Comment by fishfacemcgee** [comment]
No one said "No" when I asked about it on Monday, so I'll knock this out next. 

@cisox @mmattax Out of curiosity, is there a reason we're using a background-image for the image as opposed to an img element? I think we'll have an easier, no-JS-necessary, resizing solution with an actual image element.

**Comment by fishfacemcgee** [comment]
I'm gonna kill this for now. Making it full square makes it way too huge and we can't reasonably implement the layout from the second mockup without moving to a two-col layout.
