### ISSUE TITLE
Rework the list items to behave on smaller screens

### ISSUE THREAD

**Issue by cisox** [suspendlabs/lstn#177]
I like the visual styling on these list items, but they're using floats and percentages. I'm not sure what's causing the issue here when the screen gets smaller but it either needs to be worked out with the current float/width system or perhaps changed to something like a grid system.

Normal
![screenshot 2015-02-22 23 11 46](https://cloud.githubusercontent.com/assets/196836/6322697/67f239e2-bae8-11e4-8fb5-3f03c65e8e2d.png)

Herp Derp
![screenshot 2015-02-22 23 12 54](https://cloud.githubusercontent.com/assets/196836/6322699/70486be8-bae8-11e4-9a82-6c96bf962d11.png)

**Comment by fishfacemcgee** [comment]
I can take a look at that next. Between bootstrap and modern CSS, we shouldn't need to float anything.
