### ISSUE TITLE
Add warning around unblocking flash

### ISSUE THREAD

**Issue by cisox** [suspendlabs/lstn#92]

**Comment by cisox** [comment]
https://gist.github.com/kirbysayshi/981510

**Comment by fishfacemcgee** [comment]
It looks like this can detect when Flash is disabled outright, but not when Flash is set to click-to-play. Looking into ways to detect that.

**Comment by fishfacemcgee** [comment]
Correction: it seems that the Gist in question is based largely around their test swf. I think I've got a solution in place, but it seems hacky/fragile. I'll get a PR together and we can discuss it.

**Comment by cisox** [comment]
We have a test.swf file available throughs swfobject and it could be used to test support. I'll check into your code, but as long as it works, I think that will be fine. Otherwise, we already have the swf through bower.

**Comment by fishfacemcgee** [comment]
@cisox I'll start poking at the test swf. Any thoughts on where this check should go? Services and Controllers aren't really supposed to do DOM manip, but then we'd **have** to do emit/broadcast to let the lack of flash be known to the rest of the app.

**Comment by fishfacemcgee** [comment]
@cisox I'm either not referencing the test file the right way or it's not what we want. Regardless, I'm not sure the file is the same as what's used in the Gist.

**Comment by cisox** [comment]
@fishfacemcgee If we have problems with the test SWF and we can't check if it's missing or just disabled, we might as well just stick to the timeout check you wrote and make sure it works as well as it can.

**Comment by fishfacemcgee** [comment]
@cisox Yeah, the test file that comes with swfobject doesn't appear to be what's referenced in the Gist, nor is it accessed the same way. We'll just want to play it by ear with what I've got as slower connections may falsely see the error.

**Comment by cisox** [comment]
@fishfacemcgee I'm going to close this issue as solved for now until we get some real world feedback.
